# Generated by Django 5.0.2 on 2024-02-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('rollno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('batch', models.CharField(max_length=10)),
                ('dept', models.CharField(max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('course', models.CharField(choices=[('BT', 'BTech'), ('MT', 'MTech'), ('PhD', 'PhD')], max_length=10)),
                ('doj', models.DateField()),
                ('sem', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
