# Generated by Django 5.0.2 on 2024-02-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_app', '0002_alter_student_dept'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=10)),
                ('semester', models.PositiveSmallIntegerField()),
                ('intended_for', models.CharField(choices=[('BT', 'BTech'), ('MT', 'MTech'), ('PhD', 'PhD')], max_length=10)),
                ('credit', models.PositiveSmallIntegerField()),
                ('teacher_id', models.CharField(max_length=10)),
            ],
        ),
    ]
