# Generated by Django 5.0.2 on 2024-02-25 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_app', '0004_remove_subject_id_alter_subject_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='teacher_id',
            field=models.CharField(max_length=20),
        ),
    ]
