# Generated by Django 5.0.2 on 2024-02-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_app', '0005_alter_subject_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(max_length=2),
        ),
    ]
