# Generated by Django 5.0.2 on 2024-02-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_app', '0006_alter_student_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.CharField(max_length=2),
        ),
    ]
