# Generated by Django 5.0.2 on 2024-03-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_app', '0008_alter_subject_teacher_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('faculty_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('phone_no', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('dept', models.CharField(max_length=100)),
                ('specialisation', models.TextField()),
                ('role', models.TextField()),
            ],
        ),
    ]
