# Generated by Django 5.0.2 on 2024-03-05 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_app', '0009_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='dept',
            field=models.CharField(choices=[('CSE', 'Computer Science and Engineering'), ('ECE', 'Electronics and Communication Engineering')], default='CSE', max_length=3),
        ),
    ]
