# Generated by Django 5.0.3 on 2024-03-30 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MIS_app', '0015_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
